
capture drop nbhd
capture drop nbhd_group
capture drop borough

* Neighborhood map
gen nbhd = ""
gen nbhd_group = ""
gen borough = ""

replace nbhd = "Allerton" if neighborhood =="Allerton"
replace nbhd_group="11" if nbhd=="Allerton"
replace borough = "Bronx" if nbhd=="Allerton"
replace nbhd = "East Village" if neighborhood =="Alphabet City"
replace nbhd_group="3" if nbhd=="Alphabet City"
replace borough = "Manhattan" if nbhd=="Alphabet City"
replace nbhd = "Arden Heights" if neighborhood =="Arden Heights"
replace nbhd_group="3" if nbhd=="Arden Heights"
replace borough = "Staten Island" if nbhd=="Arden Heights"
replace nbhd = "Astoria" if neighborhood =="Astoria"
replace nbhd_group="1" if nbhd=="Astoria"
replace borough = "Queens" if nbhd=="Astoria"
replace nbhd = "Battery Park City" if neighborhood =="Battery Park City" 
replace nbhd_group="1" if nbhd=="Battery Park City"
replace borough = "Manhattan" if nbhd=="Battery Park City"
replace nbhd = "Baychester" if neighborhood =="Baychester"
replace nbhd_group="12" if nbhd=="Baychester"
replace borough = "Bronx" if nbhd=="Baychester"
replace nbhd = "Bayside" if neighborhood =="Bayside"
replace nbhd_group="11" if nbhd=="Bayside"
replace borough = "Queens" if nbhd=="Bayside"
replace nbhd = "Bedford Park" if neighborhood =="Bedford Park"
replace nbhd_group="7" if nbhd=="Bedford Park"
replace borough = "Bronx" if nbhd=="Bedford Park"
replace nbhd = "Bedford Stuyvesant" if neighborhood =="Bedford-Stuyvesant"
replace nbhd_group="3" if nbhd=="Bedford Stuyvesant"
replace borough = "Brooklyn" if nbhd=="Bedford Stuyvesant"
replace nbhd = "Bellerose" if neighborhood =="Bellerose"
replace nbhd_group="13" if nbhd=="Bellerose"
replace borough = "Queens" if nbhd=="Bellerose"
replace nbhd = "Bronxdale" if neighborhood =="Bronxdale"
replace nbhd_group="11" if nbhd=="Bronxdale"
replace borough = "Bronx" if nbhd=="Bronxdale"
replace nbhd = "Brooklyn Heights" if neighborhood =="Brooklyn Heights"
replace nbhd_group="2" if nbhd=="Brooklyn Heights"
replace borough = "Brooklyn" if nbhd=="Brooklyn Heights"
replace nbhd = "Navy Yard" if neighborhood =="Brooklyn Navy Yard"
replace nbhd_group="2" if nbhd=="Navy Yard"
replace borough = "Brooklyn" if nbhd=="Navy Yard"
replace nbhd = "Brownsville" if neighborhood =="Brownsville"
replace nbhd_group="16" if nbhd=="Brownsville"
replace borough = "Brooklyn" if nbhd=="Brownsville"
replace nbhd = "Bulls Head" if neighborhood =="Bull's Head"
replace nbhd_group="2" if nbhd=="Bulls Head"
replace borough = "Staten Island" if nbhd=="Bulls Head"
replace nbhd = "Bushwick" if neighborhood =="Bushwick"
replace nbhd_group="4" if nbhd=="Bushwick"
replace borough = "Brooklyn" if nbhd=="Bushwick"
replace nbhd = "Cambria Heights" if neighborhood =="Cambria Heights"
replace nbhd_group="13" if nbhd=="Cambria Heights"
replace borough = "Queens" if nbhd=="Cambria Heights"
replace nbhd = "Canarsie" if neighborhood =="Canarsie"
replace nbhd_group="18" if nbhd=="Canarsie"
replace borough = "Brooklyn" if nbhd=="Canarsie"
replace nbhd = "Carroll Gardens" if neighborhood =="Carroll Gardens"
replace nbhd_group="6" if nbhd=="Carroll Gardens"
replace borough = "Brooklyn" if nbhd=="Carroll Gardens"
replace nbhd = "Castle Hill" if neighborhood =="Castle Hill"
replace nbhd_group="9" if nbhd=="Castle Hill"
replace borough = "Bronx" if nbhd=="Castle Hill"
replace nbhd = "Chelsea" if neighborhood =="Chelsea"
replace nbhd_group="4" if nbhd=="Chelsea" 
replace borough = "Manhattan" if nbhd=="Chelsea" 
replace nbhd = "Chelsea" if neighborhood =="Chelsea, Staten Island"
replace nbhd_group="2" if neighborhood=="Chelsea, Staten Island"
replace borough = "Staten Island" if neighborhood=="Chelsea, Staten Island"
replace nbhd = "Chinatown" if neighborhood =="Chinatown"
replace nbhd_group="3" if nbhd=="Chinatown"
replace borough = "Manhattan" if nbhd=="Chinatown"
replace nbhd = "City Island" if neighborhood =="City Island"
replace nbhd_group="10" if nbhd=="City Island"
replace borough = "Bronx" if nbhd=="City Island"
replace nbhd = "Civic Center" if neighborhood =="Civic Center" 
replace nbhd_group="1" if nbhd=="Civic Center" 
replace borough = "Manhattan" if nbhd=="Civic Center" 
replace nbhd = "Claremont Village" if neighborhood =="Claremont"  //check once
replace nbhd_group="3" if nbhd=="Claremont Village"
replace borough = "Bronx" if nbhd=="Claremont Village"
replace nbhd = "Clifton" if neighborhood =="Clifton"
replace nbhd_group="1" if nbhd=="Clifton"
replace borough = "Staten Island" if nbhd=="Clifton"
replace nbhd = "Clinton Hill" if neighborhood =="Clinton Hill"
replace nbhd_group="2" if nbhd=="Clinton Hill"
replace borough = "Brooklyn" if nbhd=="Clinton Hill"
replace nbhd = "Co-op City" if neighborhood =="Co-op City"
replace nbhd_group="10" if nbhd=="Co-op City"
replace borough = "Bronx" if nbhd=="Co-op City"
replace nbhd = "Cobble Hill" if neighborhood =="Cobble Hill"
replace nbhd_group="6" if nbhd=="Cobble Hill"
replace borough = "Brooklyn" if nbhd=="Cobble Hill"
replace nbhd = "College Point" if neighborhood =="College Point"
replace nbhd_group="7" if nbhd=="College Point"
replace borough = "Queens" if nbhd=="College Point"
replace nbhd = "Carroll Gardens" if neighborhood =="Columbia Street Waterfront" //should be in brooklyn
replace nbhd_group="6" if nbhd=="Carroll Gardens"
replace borough = "Brooklyn" if nbhd=="Carroll Gardens"
replace nbhd = "Concord" if neighborhood =="Concord"
replace nbhd_group="2" if nbhd=="Concord"
replace borough = "Staten Island" if nbhd=="Concord"
replace nbhd = "Concourse" if neighborhood =="Concourse"
replace nbhd_group="4" if nbhd=="Concourse"
replace borough = "Bronx" if nbhd=="Concourse"
replace nbhd = "Concourse Village" if neighborhood =="Concourse Village"
replace nbhd_group="4" if nbhd=="Concourse Village"
replace borough = "Bronx" if nbhd=="Concourse Village"
replace nbhd = "Coney Island" if neighborhood =="Coney Island" 
replace nbhd_group="13" if nbhd=="Coney Island" 
replace borough = "Brooklyn" if nbhd=="Coney Island" 
replace nbhd = "Corona" if neighborhood =="Corona"
replace nbhd_group="4" if nbhd=="Corona"
replace borough = "Queens" if nbhd=="Corona"
replace nbhd = "Country Club" if neighborhood =="Country Club"
replace nbhd_group="10" if nbhd=="Country Club"
replace borough = "Bronx" if nbhd=="Country Club"
replace nbhd = "Claremont Village" if neighborhood =="Crotona"
replace nbhd_group="3" if nbhd=="Claremont Village"
replace borough = "Bronx" if nbhd=="Claremont Village"
replace nbhd = "Crown Heights" if neighborhood =="Crown Heights"
replace nbhd_group="8" if nbhd=="Crown Heights"
replace borough = "Brooklyn" if nbhd=="Crown Heights"
replace nbhd = "Dumbo" if neighborhood =="DUMBO"
replace nbhd_group="2" if nbhd=="Dumbo"
replace borough = "Brooklyn" if nbhd=="Dumbo"
replace nbhd = "Steinway" if neighborhood =="Ditmars / Steinway" | neighborhood =="Ditmars/Steinway"
replace nbhd_group="1" if nbhd=="Steinway"
replace borough = "Queens" if nbhd=="Steinway"
replace nbhd = "Dongan Hills" if neighborhood =="Dongan Hills"
replace nbhd_group="2" if nbhd=="Dongan Hills"
replace borough = "Staten Island" if nbhd=="Dongan Hills"
replace nbhd = "Douglaston" if neighborhood =="Douglaston"
replace nbhd_group="11" if nbhd=="Douglaston"
replace borough = "Queens" if nbhd=="Douglaston"
replace nbhd = "Downtown" if neighborhood =="Downtown Brooklyn"
replace nbhd_group="2" if nbhd=="Downtown"
replace borough = "Brooklyn" if nbhd=="Downtown"
replace nbhd = "Dyker Heights" if neighborhood =="Dyker Heights"
replace nbhd_group="10" if nbhd=="Dyker Heights"
replace borough = "Brooklyn" if nbhd=="Dyker Heights"
replace nbhd = "East Elmhurst" if neighborhood =="East Elmhurst"
replace nbhd_group="3" if nbhd=="East Elmhurst"
replace borough = "Queens" if nbhd=="East Elmhurst"
replace nbhd = "East Flatbush" if neighborhood =="East Flatbush"
replace nbhd_group="17" if nbhd=="East Flatbush"
replace borough = "Brooklyn" if nbhd=="East Flatbush"
replace nbhd = "East Harlem" if neighborhood =="East Harlem"
replace nbhd_group="11" if nbhd=="East Harlem"
replace borough = "Manhattan" if nbhd=="East Harlem"
replace nbhd = "East New York" if neighborhood =="East New York"
replace nbhd_group="5" if nbhd=="East New York"
replace borough = "Brooklyn" if nbhd=="East New York"
replace nbhd = "East Village" if neighborhood =="East Village" 
replace nbhd_group="3" if nbhd=="East Village" 
replace borough = "Manhattan" if nbhd=="East Village" 
replace nbhd = "Eastchester" if neighborhood =="Eastchester"
replace nbhd_group="12" if nbhd=="Eastchester"
replace borough = "Bronx" if nbhd=="Eastchester"
replace nbhd = "Edenwald" if neighborhood =="Edenwald"
replace nbhd_group="12" if nbhd=="Edenwald"
replace borough = "Bronx" if nbhd=="Edenwald"
replace nbhd = "Elm Park" if neighborhood =="Elm Park"
replace nbhd_group="1" if nbhd=="Elm Park"
replace borough = "Staten Island" if nbhd=="Elm Park"
replace nbhd = "Elmhurst" if neighborhood =="Elmhurst"
replace nbhd_group="4" if nbhd=="Elmhurst"
replace borough = "Queens" if nbhd=="Elmhurst"
replace nbhd = "Eltingville" if neighborhood =="Eltingville" 
replace nbhd_group="3" if nbhd=="Eltingville" 
replace borough = "Staten Island" if nbhd=="Eltingville" 
replace nbhd = "Emerson Hill" if neighborhood =="Emerson Hill"
replace nbhd_group="2" if nbhd=="Emerson Hill"
replace borough = "Staten Island" if nbhd=="Emerson Hill"
replace nbhd = "Fieldston" if neighborhood =="Fieldston"
replace nbhd_group="8" if nbhd=="Fieldston"
replace borough = "Bronx" if nbhd=="Fieldston"
replace nbhd = "Financial District" if neighborhood =="Financial District"
replace nbhd_group="1" if nbhd=="Financial District"
replace borough = "Manhattan" if nbhd=="Financial District"
replace nbhd = "Flatbush" if neighborhood =="Flatbush"
replace nbhd_group="14" if nbhd=="Flatbush"
replace borough = "Brooklyn" if nbhd=="Flatbush"
replace nbhd = "Flatiron" if neighborhood =="Flatiron District" //check
replace nbhd_group="5" if nbhd=="Flatiron"
replace borough = "Manhattan" if nbhd=="Flatiron"
replace nbhd = "Flatlands" if neighborhood =="Flatlands" 
replace nbhd_group="18" if nbhd=="Flatlands"
replace borough = "Brooklyn" if nbhd=="Flatlands"
replace nbhd = "Floyd Bennet Field" if neighborhood =="Floyd Bennet"
replace nbhd_group="18" if nbhd=="Floyd Bennet Field"
replace borough = "Brooklyn" if nbhd=="Floyd Bennet Field"
replace nbhd = "Flushing" if neighborhood =="Flushing"
replace nbhd_group="7" if nbhd=="Flushing"
replace borough = "Queens" if nbhd=="Flushing"
replace nbhd = "Flushing Meadows Corona Park" if neighborhood =="Flushing Meadows"
replace nbhd_group="7" if nbhd=="Flushing Meadows Corona Park"  //check group number
replace borough = "Queens" if nbhd=="Flushing Meadows Corona Park"
replace nbhd = "Fordham" if neighborhood =="Fordham"
replace nbhd_group="5" if nbhd=="Fordham"
replace borough = "Bronx" if nbhd=="Fordham"
replace nbhd = "Forest Hills" if neighborhood =="Forest Hills"
replace nbhd_group="6" if nbhd=="Forest Hills"
replace borough = "Queens" if nbhd=="Forest Hills"
replace nbhd = "Fort Greene" if neighborhood =="Fort Greene"
replace nbhd_group="2" if nbhd=="Fort Greene"
replace borough = "Brooklyn" if nbhd=="Fort Greene"
replace nbhd = "Fort Hamilton" if neighborhood =="Fort Hamilton"
replace nbhd_group="10" if nbhd=="Fort Hamilton"
replace borough = "Brooklyn" if nbhd=="Fort Hamilton"
replace nbhd = "Fort Wadsworth" if neighborhood =="Fort Wadsworth"
replace nbhd_group="1" if nbhd=="Fort Wadsworth"
replace borough = "Staten Island" if nbhd=="Fort Wadsworth"
replace nbhd = "Fresh Meadows" if neighborhood =="Fresh Meadows"
replace nbhd_group="8" if nbhd=="Fresh Meadows"
replace borough = "Queens" if nbhd=="Fresh Meadows"
replace nbhd = "Gerritsen Beach" if neighborhood =="Gerritsen Beach"
replace nbhd_group="15" if nbhd=="Gerritsen Beach"
replace borough = "Brooklyn" if nbhd=="Gerritsen Beach"
replace nbhd = "Glen Oaks" if neighborhood =="Glen Oaks"
replace nbhd_group="13" if nbhd=="Glen Oaks"
replace borough = "Queens" if nbhd=="Glen Oaks"
replace nbhd = "Glendale" if neighborhood =="Glendale"
replace nbhd_group="5" if nbhd=="Glendale"
replace borough = "Queens" if nbhd=="Glendale"
replace nbhd = "Gowanus" if neighborhood =="Gowanus"
replace nbhd_group="6" if nbhd=="Gowanus"
replace borough = "Brooklyn" if nbhd=="Gowanus"
replace nbhd = "Gramercy" if neighborhood =="Gramercy Park"
replace nbhd_group="6" if nbhd=="Gramercy"
replace borough = "Manhattan" if nbhd=="Gramercy"
replace nbhd = "Gramercy" if neighborhood =="Gramercy"
replace nbhd_group="6" if nbhd=="Gramercy"
replace borough = "Manhattan" if nbhd=="Gramercy"
replace nbhd = "Graniteville" if neighborhood =="Graniteville"
replace nbhd_group="1" if nbhd=="Graniteville"
replace borough = "Staten Island" if nbhd=="Graniteville"
replace nbhd = "Grant City" if neighborhood =="Grant City"
replace nbhd_group="2" if nbhd=="Grant City"
replace borough = "Staten Island" if nbhd=="Grant City"
replace nbhd = "Grasmere" if neighborhood =="Grasmere"
replace nbhd_group="2" if nbhd=="Grasmere"
replace borough = "Staten Island" if nbhd=="Grasmere"
replace nbhd = "Gravesend" if neighborhood =="Gravesend"
replace nbhd_group="15" if nbhd=="Gravesend"
replace borough = "Brooklyn" if nbhd=="Gravesend"
replace nbhd = "Great Kills" if neighborhood =="Great Kills"
replace nbhd_group="3" if nbhd=="Great Kills"
replace borough = "Staten Island" if nbhd=="Great Kills"
replace nbhd = "Greenpoint" if neighborhood =="Greenpoint"
replace nbhd_group="1" if nbhd=="Greenpoint"
replace borough = "Brooklyn" if nbhd=="Greenpoint"
replace nbhd = "Greenwich Village" if neighborhood =="Greenwich Village"
replace nbhd_group="2" if nbhd=="Greenwich Village"
replace borough = "Manhattan" if nbhd=="Greenwich Village"
replace nbhd = "Greenwood Cemetery" if neighborhood =="Greenwood Heights" //check
replace nbhd_group="7" if nbhd=="Greenwood Cemetery"
replace borough = "Brooklyn" if nbhd=="Greenwood Cemetery"
replace nbhd = "Grymes Hill" if neighborhood =="Grymes Hill"
replace nbhd_group="1" if nbhd=="Grymes Hill"
replace borough = "Staten Island" if nbhd=="Grymes Hill"
replace nbhd = "Central Harlem" if neighborhood =="Harlem"  //there isn't any neighbourhood called only "harlem". East and central harlem is in Manahattan in group 10 and 11
replace nbhd_group="11" if nbhd== "Central Harlem" 
replace borough = "Manhattan" if nbhd== "Central Harlem" 
replace nbhd = "Clinton" if neighborhood =="Hell's Kitchen" //no Hail's kitchen on map but hail's kitchen is also known as Clinton and there is clinton on map
replace nbhd_group="4" if nbhd=="Clinton"
replace borough = "Manhattan" if nbhd=="Clinton"
replace nbhd = "Highbridge" if neighborhood =="Highbridge"
replace nbhd_group="4" if nbhd=="Highbridge"
replace borough = "Bronx" if nbhd=="Highbridge"
replace nbhd = "Hillcrest" if neighborhood =="Hillcrest"
replace nbhd_group="8" if nbhd=="Hillcrest"
replace borough = "Queens" if nbhd=="Hillcrest"
replace nbhd = "Howard Beach" if neighborhood =="Howard Beach"
replace nbhd_group="10" if nbhd=="Howard Beach"
replace borough = "Queens" if nbhd=="Howard Beach"
replace nbhd = "Hudson Square" if neighborhood =="Hudson Square"
replace nbhd_group="2" if nbhd=="Hudson Square"
replace borough = "Manhattan" if nbhd=="Hudson Square"
replace nbhd = "Huguenot" if neighborhood =="Huguenot"
replace nbhd_group="3" if nbhd=="Huguenot"
replace borough = "Staten Island" if nbhd=="Huguenot"
replace nbhd = "Hunts Point" if neighborhood =="Hunts Point"
replace nbhd_group="2" if nbhd=="Hunts Point"
replace borough = "Bronx" if nbhd=="Hunts Point"
replace nbhd = "Inwood" if neighborhood =="Inwood" 
replace nbhd_group="12" if nbhd=="Inwood" 
replace borough = "Manhattan" if nbhd=="Inwood" 
replace nbhd = "Jackson Heights" if neighborhood =="Jackson Heights"
replace nbhd_group="3" if nbhd=="Jackson Heights"
replace borough = "Queens" if nbhd=="Jackson Heights"
replace nbhd = "Jamaica Center" if neighborhood =="Jamaica"   // there is jamaica hills/estates/center in Queens
replace nbhd_group="12" if nbhd=="Jamaica Center"
replace borough = "Queens" if nbhd=="Jamaica Center"
replace nbhd = "Kensington" if neighborhood =="Kensington"
replace nbhd_group="12" if nbhd=="Kensington"
replace borough = "Brooklyn" if nbhd=="Kensington"
replace nbhd = "Kew Garden Hills" if neighborhood =="Kew Garden Hills"
replace nbhd_group="8" if nbhd=="Kew Garden Hills"
replace borough = "Queens" if nbhd=="Kew Garden Hills"
replace nbhd = "Kingsbridge" if neighborhood =="Kingsbridge"
replace nbhd_group="8" if nbhd=="Kingsbridge"
replace borough = "Bronx" if nbhd=="Kingsbridge"
replace nbhd = "Kingsbridge Heights" if neighborhood =="Kingsbridge Heights"
replace nbhd_group="8" if nbhd=="Kingsbridge Heights"
replace borough = "Bronx" if nbhd=="Kingsbridge Heights"
replace nbhd = "Kips Bay" if neighborhood =="Kips Bay" // didn't find, should be in Mahattan
replace nbhd_group="6" if nbhd=="Kips Bay"
replace borough = "Manhattan" if nbhd=="Kips Bay"
replace nbhd = "Prospect Lefferts Garden" if neighborhood =="Lefferts Garden"
replace nbhd_group="9" if nbhd=="Prospect Lefferts Garden"
replace borough = "Brooklyn" if nbhd=="Prospect Lefferts Garden"
replace nbhd = "Lighthouse Hill" if neighborhood =="Lighthouse HIll"
replace nbhd_group="2" if nbhd=="Lighthouse Hill"
replace borough = "Staten Island" if nbhd=="Lighthouse Hill" 
replace nbhd = "Lindenwood" if neighborhood =="Lindenwood"
replace nbhd_group="10" if nbhd=="Lindenwood"
replace borough = "Queens" if nbhd=="Lindenwood"
replace nbhd = "Little Italy" if neighborhood =="Little Italy"
replace nbhd_group="2" if nbhd=="Little Italy"
replace borough = "Manhattan" if nbhd=="Little Italy"
replace nbhd = "Little Neck" if neighborhood =="Little Neck"
replace nbhd_group="11" if nbhd=="Little Neck"
replace borough = "Queens" if nbhd=="Little Neck"
replace nbhd = "Long Island City" if neighborhood =="Long Island City" 
replace nbhd_group="2" if nbhd=="Long Island City" 
replace borough = "Queens" if nbhd=="Long Island City" 
replace nbhd = "Lower East Side" if neighborhood =="Lower East Side"
replace nbhd_group="3" if nbhd=="Lower East Side"
replace borough = "Manhattan" if nbhd=="Lower East Side"
replace nbhd = "Manhattan Beach" if neighborhood =="Manhattan Beach"
replace nbhd_group="15" if nbhd=="Manhattan Beach"
replace borough = "Brooklyn" if nbhd=="Manhattan Beach"
replace nbhd = "Marble Hill" if neighborhood =="Marble Hill"
replace nbhd_group="8" if nbhd=="Marble Hill"
replace borough = "Bronx" if nbhd=="Marble Hill"
replace nbhd = "Marine Park" if neighborhood =="Marine Park"
replace nbhd_group="18" if nbhd=="Marine Park"
replace borough = "Brooklyn" if nbhd=="Marine Park"
replace nbhd = "Mariner's Harbor" if neighborhood =="Mariners Harbor" 
replace nbhd_group="1" if nbhd=="Mariner's Harbor" 
replace borough = "Staten Island" if nbhd=="Mariner's Harbor" 
replace nbhd = "Maspeth" if neighborhood =="Maspeth"
replace nbhd_group="5" if nbhd=="Maspeth"
replace borough = "Queens" if nbhd=="Maspeth"
replace nbhd = "West Village" if neighborhood =="Meatpacking District"
replace nbhd_group="2" if nbhd=="West Village"
replace borough = "Manhattan" if nbhd=="West Village"
replace nbhd = "Westerleigh" if neighborhood =="Meiers Corners" //Staten Island
replace nbhd_group="1" if nbhd=="Westerleigh"
replace borough = "Staten Island" if nbhd=="Westerleigh"
replace nbhd = "Melrose" if neighborhood =="Melrose"
replace nbhd_group="1" if nbhd=="Melrose"
replace borough = "Bronx" if nbhd=="Melrose"
replace nbhd = "Middle Village" if neighborhood =="Middle Village"
replace nbhd_group="5" if nbhd=="Middle Village"
replace borough = "Queens" if nbhd=="Middle Village"
replace nbhd = "Midland Beach" if neighborhood =="Midland Beach" 
replace nbhd_group="2" if nbhd=="Midland Beach" 
replace borough = "Staten Island" if nbhd=="Midland Beach" 
replace nbhd = "Midtown" if neighborhood =="Midtown"
replace nbhd_group="5" if nbhd=="Midtown"
replace borough = "Manhattan" if nbhd=="Midtown"
replace nbhd = "Midtown East" if neighborhood =="Midtown East" // Midtown South is in Manhattan
replace nbhd_group="5" if nbhd=="Midtown East"
replace borough = "Manhattan" if nbhd=="Midtown East"
replace nbhd = "Midwood" if neighborhood =="Midwood"
replace nbhd_group="14" if nbhd=="Midwood"
replace borough = "Brooklyn" if nbhd=="Midwood"
replace nbhd = "Mill Basin" if neighborhood =="Mill Basin"
replace nbhd_group="18" if nbhd=="Mill Basin"
replace borough = "Brooklyn" if nbhd=="Mill Basin"
replace nbhd = "Morningside Heights" if neighborhood =="Morningside Heights"
replace nbhd_group="9" if nbhd=="Morningside Heights"
replace borough = "Manhattan" if nbhd=="Morningside Heights"
replace nbhd = "Morris Heights" if neighborhood =="Morris Heights"
replace nbhd_group="5" if nbhd=="Morris Heights"
replace borough = "Bronx" if nbhd=="Morris Heights" 
replace nbhd = "Morrisania" if neighborhood =="Morrisania"
replace nbhd_group="3" if nbhd=="Morrisania"
replace borough = "Bronx" if nbhd=="Morrisania"
replace nbhd = "Mott Haven" if neighborhood =="Mott Haven"
replace nbhd_group="1" if nbhd=="Mott Haven"
replace borough = "Bronx" if nbhd=="Mott Haven"
replace nbhd = "Mount Eden" if neighborhood =="Mount Eden"
replace nbhd_group="4" if nbhd=="Mount Eden"
replace borough = "Bronx" if nbhd=="Mount Eden"
replace nbhd = "Murray Hill" if neighborhood =="Murray Hill"
replace nbhd_group="6" if nbhd=="Murray Hill"
replace borough = "Manhattan" if nbhd=="Murray Hill"
replace nbhd = "New Brighton" if neighborhood =="New Brighton"
replace nbhd_group="1" if nbhd=="New Brighton"
replace borough = "Staten Island" if nbhd=="New Brighton"
replace nbhd = "New Dorp" if neighborhood =="New Dorp"
replace nbhd_group="2" if nbhd=="New Dorp"
replace borough = "Staten Island" if nbhd=="New Dorp"
replace nbhd = "New Dorp Beach" if neighborhood =="New Dorp Beach"
replace nbhd_group="2" if nbhd=="New Dorp Beach"
replace borough = "Staten Island" if nbhd=="New Dorp Beach"
replace nbhd = "New Springville" if neighborhood =="New Springville"
replace nbhd_group="2" if nbhd=="New Springville"
replace borough = "Staten Island" if nbhd=="New Springville"
replace nbhd = "NoHo" if neighborhood =="Noho"
replace nbhd_group="3" if nbhd=="NoHo"
replace borough = "Staten Island" if nbhd=="NoHo"
replace nbhd = "Little Italy" if neighborhood =="Nolita"  
replace nbhd_group="2" if nbhd=="Little Italy"
replace borough = "Manhattan" if nbhd=="Little Italy"
replace nbhd = "North Riverdale" if neighborhood =="North Riverdale"
replace nbhd_group="8" if nbhd=="North Riverdale"
replace borough = "Bronx" if nbhd=="North Riverdale"
replace nbhd = "Norwood" if neighborhood =="Norwood"
replace nbhd_group="7" if nbhd=="Norwood"
replace borough = "Bronx" if nbhd=="Norwood"
replace nbhd = "Oakwood" if neighborhood =="Oakwood"
replace nbhd_group="3" if nbhd=="Oakwood"
replace borough = "Staten Island" if nbhd=="Oakwood"
replace nbhd = "Ozone Park" if neighborhood =="Ozone Park"
replace nbhd_group="10" if nbhd=="Ozone Park"
replace borough = "Queens" if nbhd=="Ozone Park"
replace nbhd = "Park Slope" if neighborhood =="Park Slope"
replace nbhd_group="6" if nbhd=="Park Slope"
replace borough = "Brooklyn" if nbhd=="Park Slope"
replace nbhd = "Parkchester" if neighborhood =="Park Versailles"
replace nbhd_group="9" if nbhd=="Parkchester"
replace borough = "Bronx" if nbhd=="Parkchester"
replace nbhd = "Parkchester" if neighborhood =="Parkchester"
replace nbhd_group="9" if nbhd=="Parkchester"
replace borough = "Bronx" if nbhd=="Parkchester"
replace nbhd = "Pelham Bay" if neighborhood =="Pelham Bay"
replace nbhd_group="10" if nbhd=="Pelham Bay"
replace borough = "Bronx" if nbhd=="Pelham Bay"
replace nbhd = "Port Morris" if neighborhood =="Port Morris"
replace nbhd_group="1" if nbhd=="Port Morris"
replace borough = "Bronx" if nbhd=="Port Morris"
replace nbhd = "Port Richmond" if neighborhood =="Port Richmond" 
replace nbhd_group="1" if nbhd=="Port Richmond" 
replace borough = "Staten Island" if nbhd=="Port Richmond" 
replace nbhd = "Prince's Bay" if neighborhood =="Prince's Bay"
replace nbhd_group="3" if nbhd=="Prince's Bay"
replace borough = "Staten Island" if nbhd=="Prince's Bay"
replace nbhd = "Prospect Heights" if neighborhood =="Prospect Heights"
replace nbhd_group="8" if nbhd=="Prospect Heights"
replace borough = "Brooklyn" if nbhd=="Prospect Heights"
replace nbhd = "Randall Manor" if neighborhood =="Randall Manor"
replace nbhd_group="1" if nbhd=="Randall Manor"
replace borough = "Staten Island" if nbhd=="Randall Manor"
replace nbhd = "Red Hook" if neighborhood =="Red Hook"
replace nbhd_group="6" if nbhd=="Red Hook"
replace borough = "Brooklyn" if nbhd=="Red Hook"
replace nbhd = "Rego Park" if neighborhood =="Rego Park"
replace nbhd_group="6" if nbhd=="Rego Park"
replace borough = "Queens" if nbhd=="Rego Park"
replace nbhd = "Richmond Hill" if neighborhood =="Richmond Hill"
replace nbhd_group="9" if nbhd=="Richmond Hill"
replace borough = "Queens" if nbhd=="Richmond Hill"
replace nbhd = "Richmond Town" if neighborhood =="Richmondtown"
replace nbhd_group="3" if nbhd=="Richmond Town"
replace borough = "Staten Island" if nbhd=="Richmond Town"
replace nbhd = "Ridgewood" if neighborhood =="Ridgewood"
replace nbhd_group="5" if nbhd=="Ridgewood"
replace borough = "Queens" if nbhd=="Ridgewood"
replace nbhd = "Riverdale" if neighborhood =="Riverdale" 
replace nbhd_group="8" if nbhd=="Riverdale" 
replace borough = "Bronx" if nbhd=="Riverdale" 
replace nbhd = "Rockaway Beach" if neighborhood =="Rockaway Beach"
replace nbhd_group="14" if nbhd=="Rockaway Beach"
replace borough = "Queens" if nbhd=="Rockaway Beach"
replace nbhd = "Roosevelt Island" if neighborhood =="Roosevelt Island" //between manhattan and queens
replace nbhd_group="8" if nbhd=="Roosevelt Island"
replace borough = "Manhattan" if nbhd=="Roosevelt Island"
replace nbhd = "Rosebank" if neighborhood =="Rosebank"
replace nbhd_group="1" if nbhd=="Rosebank"
replace borough = "Staten Island" if nbhd=="Rosebank"
replace nbhd = "Sea Gate" if neighborhood =="Sea Gate"
replace nbhd_group="13" if nbhd=="Sea Gate"
replace borough = "Brooklyn" if nbhd=="Sea Gate"
replace nbhd = "Sheepshead Bay" if neighborhood =="Sheepshead Bay"
replace nbhd_group="15" if nbhd=="Sheepshead Bay"
replace borough = "Brooklyn" if nbhd=="Sheepshead Bay"
replace nbhd = "Silver Lake" if neighborhood =="Silver Lake"
replace nbhd_group="1" if nbhd=="Silver Lake"
replace borough = "Staten Island" if nbhd=="Silver Lake"
replace nbhd = "SoHo" if neighborhood =="SoHo" | neighborhood =="Soho" 
replace nbhd_group="2" if nbhd=="SoHo"
replace borough = "Manhattan" if nbhd=="SoHo"
replace nbhd = "Soundview" if neighborhood =="Soundview"
replace nbhd_group="9" if nbhd=="Soundview"
replace borough = "Bronx" if nbhd=="Soundview"
replace nbhd = "South Beach" if neighborhood =="South Beach"
replace nbhd_group="2" if nbhd=="South Beach"
replace borough = "Staten Island" if nbhd=="South Beach"
replace nbhd = "South Ozone Park" if neighborhood =="South Ozone Park"
replace nbhd_group="10" if nbhd=="South Ozone Park"
replace borough = "Queens" if nbhd=="South Ozone Park"
replace nbhd = "Financial District" if neighborhood =="South Street Seaport"
replace nbhd_group="1" if nbhd=="Financial District"
replace borough = "Manhattan" if nbhd=="Financial District"
replace nbhd = "Spuyten Duyvil" if neighborhood =="Spuyten Duyvil" 
replace nbhd_group="8" if nbhd=="Spuyten Duyvil" 
replace borough = "Bronx" if nbhd=="Spuyten Duyvil" 
replace nbhd = "ST. George" if neighborhood =="St. George" 
replace nbhd_group="1" if nbhd=="ST. George" 
replace borough = "Staten Island" if nbhd=="ST. George" 
replace nbhd = "Stapleton" if neighborhood =="Stapleton"
replace nbhd_group="1" if nbhd=="Stapleton"
replace borough = "Staten Island" if nbhd=="Stapleton"
replace nbhd = "Stuyvesant Town" if neighborhood =="Stuyvesant Town"
replace nbhd_group="6" if nbhd=="Stuyvesant Town"
replace borough = "Manhattan" if nbhd=="Stuyvesant Town"
replace nbhd = "Sunnyside" if neighborhood =="Sunnyside" | neighborhood =="Sunnyside Queens"
replace nbhd_group="2" if nbhd=="Sunnyside"
replace borough = "Queens" if nbhd=="Sunnyside"
replace nbhd = "Sunset Park" if neighborhood =="Sunset Park"
replace nbhd_group="7" if nbhd=="Sunset Park"
replace borough = "Brooklyn" if nbhd=="Sunset Park"
replace nbhd = "The Rockaways" if neighborhood =="The Rockaways" // Rockway beach and park in Queens group 14
replace nbhd_group="14" if nbhd=="The Rockaways"
replace borough = "Queens" if nbhd=="The Rockaways"
replace nbhd = "Throgs Neck" if neighborhood =="Throgs Neck"
replace nbhd_group="10" if nbhd=="Throgs Neck"
replace borough = "Bronx" if nbhd=="Throgs Neck"
replace nbhd = "Times Square" if neighborhood =="Times Square Theatre District" //keeping as Times Square
replace nbhd_group="5" if nbhd=="Times Square"
replace borough = "Manhattan" if nbhd=="Times Square"
replace nbhd = "Todt Hill" if neighborhood =="Todt Hill"
replace nbhd_group="2" if nbhd=="Todt Hill"
replace borough = "Staten Island" if nbhd=="Todt Hill"
replace nbhd = "Tompkinsville" if neighborhood =="Tompkinsville"
replace nbhd_group="1" if nbhd=="Tompkinsville"
replace borough = "Staten Island" if nbhd=="Tompkinsville"
replace nbhd = "Tottenville" if neighborhood =="Tottenville"
replace nbhd_group="3" if nbhd=="Tottenville"
replace borough = "Staten Island" if nbhd=="Tottenville"
replace nbhd = "East Tremont" if neighborhood =="Tremont" //check, could not find Tremont
replace nbhd_group="6" if nbhd=="East Tremont"
replace borough = "Bronx" if nbhd=="East Tremont"
replace nbhd = "Tribeca" if neighborhood =="Tribeca" 
replace nbhd_group="3" if nbhd=="Tribeca"
replace borough = "Manhattan" if nbhd=="Tribeca"
replace nbhd = "Union Square" if neighborhood =="Union Square"
replace nbhd_group="5" if nbhd=="Union Square"
replace borough = "Manhattan" if nbhd=="Union Square"
replace nbhd = "University Heights" if neighborhood =="University Heights"
replace nbhd_group="5" if nbhd=="University Heights"
replace borough = "Bronx" if nbhd=="University Heights"
replace nbhd = "Upper East Side" if neighborhood =="Upper East Side"
replace nbhd_group="8" if nbhd=="Upper East Side"
replace borough = "Manhattan" if nbhd=="Upper East Side"
replace nbhd = "Upper West Side" if neighborhood =="Upper West Side" 
replace nbhd_group="7" if nbhd=="Upper West Side" 
replace borough = "Manhattan" if nbhd=="Upper West Side" 
replace nbhd = "Utopia" if neighborhood =="Utopia"
replace nbhd_group="8" if nbhd=="Utopia"
replace borough = "Queens" if nbhd=="Utopia"
replace nbhd = "Van Nest" if neighborhood =="Van Nest"
replace nbhd_group="11" if nbhd=="Van Nest"
replace borough = "Bronx" if nbhd=="Van Nest"
replace nbhd = "Vinegar Hill" if neighborhood =="Vinegar Hill"
replace nbhd_group="2" if nbhd=="Vinegar Hill"
replace borough = "Brooklyn" if nbhd=="Vinegar Hill"
replace nbhd = "Wakefield" if neighborhood =="Wakefield"
replace nbhd_group="12" if nbhd=="Wakefield"
replace borough = "Bronx" if nbhd=="Wakefield"
replace nbhd = "Washington Heights" if neighborhood =="Washington Heights" 
replace nbhd_group="12" if nbhd=="Washington Heights" 
replace borough = "Manhattan" if nbhd=="Washington Heights" 
replace nbhd = "West Brighton" if neighborhood =="West Brighton"
replace nbhd_group="1" if nbhd=="West Brighton"
replace borough = "Staten Island" if nbhd=="West Brighton"
replace nbhd = "West Farms" if neighborhood =="West Farms"
replace nbhd_group="6" if nbhd=="West Farms"
replace borough = "Bronx" if nbhd=="West Farms"
replace nbhd = "West Village" if neighborhood =="West Village" 
replace nbhd_group="2" if nbhd=="West Village" 
replace borough = "Manhattan" if nbhd=="West Village" 
replace nbhd = "Westchester Square" if neighborhood =="Westchester Square"
replace nbhd_group="10" if nbhd=="Westchester Square"
replace borough = "Bronx" if nbhd=="Westchester Square"
replace nbhd = "Westerleigh" if neighborhood =="Westerleigh"
replace nbhd_group="1" if nbhd=="Westerleigh"
replace borough = "Manhattan" if nbhd=="Westerleigh"
replace nbhd = "Whitestone" if neighborhood =="Whitestone"
replace nbhd_group="7" if nbhd=="Whitestone"
replace borough = "Queens" if nbhd=="Whitestone"
replace nbhd = "Williamsbridge" if neighborhood =="Williamsbridge"
replace nbhd_group="12" if nbhd=="Williamsbridge"
replace borough = "Bronx" if nbhd=="Williamsbridge"
replace nbhd = "Williamsburg" if neighborhood =="Williamsburg"
replace nbhd_group="1" if nbhd=="Williamsburg"
replace borough = "Brooklyn" if nbhd=="Williamsburg"
replace nbhd = "Willowbrook" if neighborhood =="Willowbrook"
replace nbhd_group="2" if nbhd=="Willowbrook"
replace borough = "Staten Island" if nbhd=="Willowbrook"
replace nbhd = "Windsor Terrace" if neighborhood =="Windsor Terrace"
replace nbhd_group="7" if nbhd=="Windsor Terrace"
replace borough = "Brooklyn" if nbhd=="Windsor Terrace"
replace nbhd = "Woodhaven" if neighborhood =="Woodhaven"
replace nbhd_group="9" if nbhd=="Woodhaven"
replace borough = "Queens" if nbhd=="Woodhaven"
replace nbhd = "Woodlawn" if neighborhood =="Woodlawn"
replace nbhd_group="12" if nbhd=="Woodlawn"
replace borough = "Bronx" if nbhd=="Woodlawn"
replace nbhd = "Woodside" if neighborhood =="Woodside"
replace nbhd_group="2" if nbhd=="Woodside"
replace borough = "Queens" if nbhd=="Woodside"
replace nbhd = "Longwood" if neighborhood =="Longwood"
replace nbhd_group="2" if nbhd=="Longwood"
replace borough = "Bronx" if nbhd=="Longwood"
replace nbhd = "Morris Park" if neighborhood =="Morris Park"
replace nbhd_group="11" if nbhd=="Morris Park"
replace borough = "Bronx" if nbhd=="Morris Park"


replace nbhd = neighborhood if nbhd == ""
replace borough = "Brooklyn" if neighborhood == "Brooklyn"
* Three columns generated that have map syncd neighborhoods
*===============================================================================
foreach lname of varlist nbhd nbhd_group borough {
	rename `lname' temp 
	encode temp, gen (`lname')
	drop temp
}



